modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT License"
issueTrackerURL = "https://github.com/daynightcycle/Serene-Seasons-Atmospheric-Crops-Compat/issues"
[[mods]]
modId = "sereneseasonsatmosphericcrops"
version = "${file.jarVersion}"
displayName = "Serene Seasons - Atmospheric - Crops Compat"
displayURL = "https://github.com/daynightcycle/Serene-Seasons-Atmospheric-Crops-Compat"
credits = "Thanks for this mod goes to Darkorg, Java, and the Forge Team."
authors = "Darkorg, daynightcycle"
description = '''Grow your crops in their respective seasons!'''

[[dependencies.sereneseasonsatmosphericcrops]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.19.2-8.1.0.24,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sereneseasonsatmosphericcrops]]
modId = "pamhc2crops"
mandatory = true
versionRange = "[5.0.0,)"
ordering = "NONE"
side = "BOTH"
